version: 0.0
os: linux

files:
  - source: /
    destination: /home/ec2-user/pioneer-pay-microservices

hooks:
  ApplicationStop:
    - location: scripts/server_stop.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/server_start.sh
      timeout: 300
      runas: root
  ValidateService:
    - location: scripts/server_validate.sh
      timeout: 300
      runas: root