server:
  port: 8085

spring:
  application:
    name: API-GATEWAY


  cloud:
    gateway:
      routes:
        - id: USER-INFO-SERVICE
          uri: lb://USER-INFO-SERVICE
          predicates:
            - Path=/api/user/**

        - id: ACCOUNT-SERVICE
          uri: lb://ACCOUNT-SERVICE
          predicates:
            - Path=/api/account/**

        - id: TRANSACTION-SERVICE
          uri: lb://TRANSACTION-SERVICE
          predicates:
            - Path=/api/**


eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

